import{useMutation,useQuery,useQueryClient}from"@tanstack/react-query";
import{AlertTriangle,CheckCircle2,LoaderCircle,RefreshCw,XCircle}from"lucide-react";
import{projectApi}from"./projectApi";
const list=(value:unknown)=>Array.isArray(value)?value:[];
const useAction=(fn:()=>Promise<unknown>,refresh:()=>void)=>useMutation({mutationFn:fn,onSuccess:refresh});
export default function ProductionBriefWorkspace({projectId}:{projectId:string}){
 const client=useQueryClient();const project=useQuery({queryKey:["project",projectId],queryFn:({signal})=>projectApi.get(projectId,signal)});const status=useQuery({queryKey:["brief-status",projectId],queryFn:({signal})=>projectApi.briefStatus(projectId,signal),enabled:Boolean(project.data&&!(["CREATED","RESEARCHING"].includes(project.data.status))),retry:false,refetchInterval:q=>["PENDING","GENERATING"].includes(q.state.data?.brief_status??"")?2000:false});const ready=["COMPLETE","NEEDS_REVIEW","APPROVED","REJECTED","STALE"].includes(status.data?.brief_status??"");const brief=useQuery({queryKey:["brief",projectId],queryFn:({signal})=>projectApi.brief(projectId,signal),enabled:ready});const refresh=()=>{client.invalidateQueries({queryKey:["project",projectId]});client.invalidateQueries({queryKey:["brief-status",projectId]});client.invalidateQueries({queryKey:["brief",projectId]})};const start=useAction(()=>projectApi.startBrief(projectId),refresh);const retry=useAction(()=>projectApi.retryBrief(projectId),refresh);const approve=useAction(()=>projectApi.approveBrief(projectId),refresh);const reject=useAction(()=>projectApi.rejectBrief(projectId),refresh);const regenerate=useAction(()=>projectApi.regenerateBrief(projectId),refresh);
 if(project.isPending)return <div className="panel p-6 text-muted">Loading project…</div>;
 if(project.data?.status==="RESEARCH_COMPLETE"&&!status.data)return <div className="panel p-8"><h2 className="page-title">Executive Producer</h2><p className="mt-3 text-sm text-muted">Transform approved research into an evidence-bounded production decision.</p><button onClick={()=>start.mutate()} className="mt-7 rounded-lg bg-accent px-5 py-3 text-sm font-bold text-white">GENERATE PRODUCTION BRIEF</button></div>;
 if(status.data?.brief_status==="FAILED")return <div className="panel p-8"><AlertTriangle className="text-danger"/><h2 className="mt-4 text-xl font-semibold">Executive Producer failed</h2><p className="mt-2 text-sm text-muted">{status.data.safe_error_message}</p><button onClick={()=>retry.mutate()} className="btn mt-6">RETRY</button></div>;
 if(!ready)return <div><h2 className="page-title">Generating Production Brief…</h2><div className="panel mt-6 flex gap-4 p-6"><LoaderCircle className="h-5 w-5 animate-spin text-accent"/><p>{status.data?.current_step.replaceAll("_"," ")} · {status.data?.candidate_angles_generated??0} angles</p></div></div>;
 if(brief.isPending||!brief.data)return <div className="panel p-6 text-muted">Loading brief…</div>;const data=brief.data.brief;
 if(brief.data.status==="STALE")return <div className="panel border-warning/30 p-8"><AlertTriangle className="text-warning"/><h2 className="mt-4 text-xl font-semibold">Production Brief is stale</h2><p className="mt-2 text-sm text-muted">Research was expanded. Regenerate this brief against the approved current dossier before Script regeneration.</p><button onClick={()=>regenerate.mutate()} className="mt-6 rounded-lg bg-accent px-5 py-3 text-sm font-bold text-white"><RefreshCw className="mr-2 inline h-4 w-4"/>REGENERATE PRODUCTION BRIEF</button></div>;
 return <div className="space-y-6"><div className="flex justify-between gap-4"><div><p className="subtle-label">Production Brief · {brief.data.version}</p><h2 className="page-title mt-2">{String(data.working_title??"Production Brief")}</h2><p className="mt-2 text-sm text-muted">{String(data.recommendation)}</p></div>{!(["APPROVED","REJECTED"].includes(brief.data.status))&&<div className="flex gap-2"><button onClick={()=>reject.mutate()} className="btn text-danger"><XCircle className="h-4 w-4"/>REJECT PROJECT</button><button onClick={()=>approve.mutate()} className="rounded-lg bg-success px-4 py-2 text-sm font-bold text-white">APPROVE PRODUCTION BRIEF</button></div>}</div>
 <section className="grid gap-4 md:grid-cols-3"><div className="panel p-5"><p className="subtle-label">Revised Money Score</p><p className="mt-3 text-3xl font-semibold">{String(data.revised_money_score)}/100</p></div><div className="panel p-5"><p className="subtle-label">Confidence</p><p className="mt-3 text-3xl font-semibold">{String(data.revised_confidence)}%</p></div><div className="panel p-5"><p className="subtle-label">Production</p><p className="mt-3 font-semibold">{String(data.estimated_production_hours)} hours</p></div></section>
 {[['Primary Angle',data.primary_angle],['Core Question',data.core_question],['Viewer Promise',data.viewer_promise],['Opening Hook',data.opening_hook]].map(([title,value])=><section className="panel p-6" key={String(title)}><h3 className="section-title">{String(title)}</h3><p className="mt-3 text-sm text-muted">{String(value)}</p></section>)}
 <section className="panel p-6"><h3 className="section-title">Candidate Angles</h3>{list(data.candidate_angles).map((item,index)=><p className="mt-3 text-sm" key={index}>{String((item as Record<string,unknown>).title)}</p>)}</section>
 <section className="panel p-6"><h3 className="section-title">Narrative Structure</h3>{list(data.key_story_beats).map((item,index)=><div className="mt-3 rounded-lg border border-line p-3" key={index}>{String((item as Record<string,unknown>).name)} · {list((item as Record<string,unknown>).supporting_fact_ids).length} facts</div>)}</section>
 {[['Monetization Risks',data.monetization_risks],['Factual Risks',data.factual_risks],['Copyright Risks',data.copyright_risks],['Limitations',data.limitations]].map(([title,items])=><section className="panel p-6" key={String(title)}><h3 className="section-title">{String(title)}</h3><ul className="mt-4 list-disc pl-5 text-sm text-muted">{list(items).map((item,index)=><li key={index}>{String(item)}</li>)}</ul></section>)}
 {brief.data.status==="APPROVED"&&<div className="flex items-center gap-3 rounded-xl border border-success/30 bg-success/10 p-5 text-success"><CheckCircle2/><strong>Production Brief approved · Script unlocked.</strong></div>}</div>;
}
