import{QueryClient,QueryClientProvider}from"@tanstack/react-query";
import{render,screen}from"@testing-library/react";
import{beforeEach,describe,expect,it,vi}from"vitest";
import ProductionBriefWorkspace from"./ProductionBriefWorkspace";
import{projectApi}from"./projectApi";

vi.mock("./projectApi",()=>({projectApi:{get:vi.fn(),briefStatus:vi.fn(),brief:vi.fn(),startBrief:vi.fn(),retryBrief:vi.fn(),approveBrief:vi.fn(),rejectBrief:vi.fn()}}));
const project={id:"p1",title:"The Great Pyramid",country:"United States",language:"English",category:"Documentary",target_length:"15 Minutes",status:"BRIEF_COMPLETE" as const,created_at:"",updated_at:""};
const status={project_id:"p1",project_status:"BRIEF_COMPLETE",brief_status:"COMPLETE",current_step:"COMPLETE",candidate_angles_generated:3,selected_angle:"Mortar evidence",recommendation:"PROCEED",revised_money_score:76,safe_error_message:null,started_at:null,completed_at:null};
function view(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><ProductionBriefWorkspace projectId="p1"/></QueryClientProvider>)}

describe("Executive Producer workspace",()=>{beforeEach(()=>vi.clearAllMocks());it("shows generation without a fake brief",async()=>{vi.mocked(projectApi.get).mockResolvedValue({...project,status:"PRODUCING_BRIEF"});vi.mocked(projectApi.briefStatus).mockResolvedValue({...status,project_status:"PRODUCING_BRIEF",brief_status:"GENERATING",current_step:"GENERATING_ANGLES"});view();expect(await screen.findByText("Generating Production Brief…")).toBeInTheDocument();expect(screen.queryByText("76/100")).not.toBeInTheDocument()});it("renders the selected evidence-led decision and approval",async()=>{vi.mocked(projectApi.get).mockResolvedValue(project);vi.mocked(projectApi.briefStatus).mockResolvedValue(status);vi.mocked(projectApi.brief).mockResolvedValue({project_id:"p1",status:"COMPLETE",version:"producer-v1",generated_at:null,approved_at:null,brief:{working_title:"Construction-material evidence",primary_angle:"Follow the surviving mortar.",core_question:"What can it establish?",viewer_promise:"Separate evidence from interpretation.",target_audience:"Documentary viewers",tone:"Rigorous",pacing:"Measured",opening_hook:"Start with the artifact.",candidate_angles:[{title:"Mortar evidence",evidence_strength:90,confidence:85}],key_story_beats:[{name:"Opening Hook",purpose:"Ask the question",supporting_source_ids:["src1"]}],revised_money_score:76,revised_confidence:82,estimated_production_hours:16,production_difficulty:55,recommendation:"PROCEED",monetization_risks:["Review required"],factual_risks:["Verify full source"],copyright_risks:["Clear museum rights"],excluded_topics:["Unsupported claims"],limitations:["No guarantee"]}});view();expect(await screen.findByText("Construction-material evidence")).toBeInTheDocument();expect(screen.getByText("76/100")).toBeInTheDocument();expect(screen.getByRole("button",{name:/approve production brief/i})).toBeInTheDocument();expect(screen.getByText("Clear museum rights")).toBeInTheDocument()})});
