import{useMutation,useQuery,useQueryClient}from"@tanstack/react-query";
import{AlertTriangle,CheckCircle2,ExternalLink,LoaderCircle}from"lucide-react";
const useLocation=()=>({search:window.location.search});
import type{ResearchFact,ResearchSource}from"../../api/types";
import{projectApi}from"./projectApi";

function Fact({fact,sources}:{fact:ResearchFact;sources:Map<string,ResearchSource>}){return <li className="rounded-lg border border-line bg-raised p-4"><p className="text-sm leading-6">{fact.claim}</p><div className="mt-3 flex flex-wrap gap-2 text-[10px] font-bold uppercase"><span className="text-success">{fact.verification_status}</span><span className="text-muted">{Math.round(fact.confidence*100)}% confidence</span>{fact.supporting_source_ids.map(id=>{const source=sources.get(id);return source?<a key={id} href={source.url} target="_blank" rel="noreferrer" className="text-accent">{source.title}</a>:null})}</div></li>}

export default function ResearchWorkspace({projectId}:{projectId:string}){
 const client=useQueryClient();const location=useLocation();const wantsExpansion=new URLSearchParams(location.search).get("expand")==="1";
 const status=useQuery({queryKey:["research-status",projectId],queryFn:({signal})=>projectApi.researchStatus(projectId,signal),refetchInterval:q=>["PENDING","RUNNING"].includes(q.state.data?.research_status??"")?2000:false});
 const complete=["COMPLETE","NEEDS_REVIEW","APPROVED"].includes(status.data?.research_status??"");
 const dossier=useQuery({queryKey:["research",projectId],queryFn:({signal})=>projectApi.research(projectId,signal),enabled:complete});
 const gaps=useQuery({queryKey:["research-gaps",projectId],queryFn:({signal})=>projectApi.researchGaps(projectId,signal),enabled:complete&&wantsExpansion,retry:false});
 const refresh=()=>{client.invalidateQueries({queryKey:["project",projectId]});client.invalidateQueries({queryKey:["research-status",projectId]});client.invalidateQueries({queryKey:["research",projectId]})};
 const retry=useMutation({mutationFn:()=>projectApi.retryResearch(projectId),onSuccess:refresh});const approve=useMutation({mutationFn:()=>projectApi.approveResearch(projectId),onSuccess:refresh});const expand=useMutation({mutationFn:()=>projectApi.expandResearch(projectId),onSuccess:refresh});
 if(status.isPending)return <div className="panel p-6 text-sm text-muted">Loading research status…</div>;
 if(status.isError)return <div className="panel p-6 text-sm text-danger">{status.error.message}</div>;
 if(status.data.research_status==="FAILED")return <div className="panel p-8"><AlertTriangle className="text-danger"/><h2 className="mt-4 text-xl font-semibold">Research failed</h2><p className="mt-2 text-sm text-muted">{status.data.error_message??"Research could not be completed."}</p><button className="btn mt-6" onClick={()=>retry.mutate()}>RETRY RESEARCH</button></div>;
 if(!complete)return <div><h2 className="page-title">Research expansion in progress…</h2><div className="panel mt-6 p-6"><div className="flex items-center gap-3"><LoaderCircle className="h-5 w-5 animate-spin text-accent"/><div><p className="font-medium">{status.data.current_step.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-muted">{status.data.sources_found} sources found · {status.data.facts_verified} facts verified</p></div><strong className="ml-auto text-sm">{status.data.progress}%</strong></div></div></div>;
 if(dossier.isPending||!dossier.data)return <div className="panel p-6 text-muted">Loading dossier…</div>;
 const data=dossier.data.dossier;const sources=new Map(data.sources.map(source=>[source.id,source]));const audit=data.expansion_history?.at(-1);
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="subtle-label">Research · {dossier.data.research_version}</p><h2 className="page-title mt-2">Source-grounded research</h2></div><div className="flex gap-2">{dossier.data.research_status==="APPROVED"&&wantsExpansion?<button onClick={()=>expand.mutate()} className="rounded-lg bg-accent px-4 py-2 text-sm font-bold text-white">EXPAND RESEARCH</button>:dossier.data.research_status!=="APPROVED"?<button onClick={()=>approve.mutate()} className="rounded-lg bg-success px-4 py-2 text-sm font-bold text-white"><CheckCircle2 className="mr-2 inline h-4 w-4"/>APPROVE RESEARCH</button>:<span className="text-sm font-semibold text-success">✓ Research approved</span>}</div></div>
 {wantsExpansion&&gaps.data&&<section className="panel border-warning/30 p-6"><h3 className="section-title">Evidence gaps</h3><div className="mt-4 grid gap-3 sm:grid-cols-4">{[["Missing facts",gaps.data.missing_facts],["Missing sources",gaps.data.missing_sources],["Missing authoritative",gaps.data.missing_authoritative_sources],["Supported maximum",`${gaps.data.recommended_max_duration_minutes} min`]].map(([label,value])=><div className="rounded-lg bg-raised p-3" key={label}><p className="subtle-label">{label}</p><p className="mt-2 font-semibold">{value}</p></div>)}</div><p className="mt-4 text-sm text-muted">Focus: {gaps.data.proposed_focus_areas.join(", ")}</p></section>}
 {audit&&<section className="panel border-accent/30 p-6"><h3 className="section-title">Latest expansion</h3><p className="mt-3 text-sm text-muted">{audit.sources_added.length} sources added · {audit.facts_added.length} facts added · downstream Production Brief and Script require regeneration.</p></section>}
 {[['Executive Summary',data.executive_summary],['Audience Interest',data.audience_interest],['Why This Topic Matters',data.why_this_topic_matters]].map(([title,text])=><section className="panel p-6" key={title}><h3 className="section-title">{title}</h3><p className="mt-4 text-sm leading-7 text-muted">{text}</p></section>)}
 {[['Key Facts',data.key_facts],['Interesting Facts',data.interesting_facts]].map(([title,facts])=><section className="panel p-6" key={title as string}><h3 className="section-title">{title as string}</h3><ul className="mt-4 space-y-3">{(facts as ResearchFact[]).map((fact,index)=><Fact key={index} fact={fact} sources={sources}/>)}</ul></section>)}
 <section className="panel p-6"><h3 className="section-title">Sources</h3>{data.sources.map(source=><article className="border-b border-line py-4" key={source.id}><a href={source.url} target="_blank" rel="noreferrer" className="font-medium">{source.title}<ExternalLink className="ml-1 inline h-3 w-3"/></a><p className="mt-1 text-xs text-muted">{source.publisher} · {source.source_quality}</p><p className="mt-2 text-sm text-muted">{source.excerpt}</p></article>)}</section>
 <section className="panel p-6"><h3 className="section-title">Story Angles</h3>{data.story_angles.map(item=><p className="mt-3 text-sm" key={item.title}>{item.title}</p>)}</section>
 <section className="panel border-warning/30 p-6"><h3 className="section-title">Limitations</h3><ul className="mt-4 list-disc pl-5 text-sm text-muted">{data.limitations.map(item=><li key={item}>{item}</li>)}</ul></section></div>;
}
