import{QueryClient,QueryClientProvider}from"@tanstack/react-query";
import{render,screen}from"@testing-library/react";
import{beforeEach,describe,expect,it,vi}from"vitest";
import ScriptWorkspace from"./ScriptWorkspace";
import{projectApi}from"./projectApi";

vi.mock("./projectApi",()=>({projectApi:{get:vi.fn(),scriptStatus:vi.fn(),script:vi.fn(),startScript:vi.fn(),approveScript:vi.fn(),retryScript:vi.fn(),regenerateScript:vi.fn(),rejectScript:vi.fn()}}));
const project={id:"p1",title:"Pyramid",country:"US",language:"English",category:"Documentary",target_length:"15 Minutes",status:"SCRIPTING" as const,created_at:"",updated_at:""};
const base={project_id:"p1",project_status:"SCRIPTING",script_status:"NEEDS_REVIEW",current_step:"EVIDENCE_INSUFFICIENT",evidence_sufficiency:"INSUFFICIENT",available_facts:1,required_facts:12,available_sources:1,required_sources:7,actual_word_count:0,target_word_count:2175,estimated_duration_minutes:null,safe_error_message:null,started_at:null,completed_at:null};
function view(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><ScriptWorkspace projectId="p1"/></QueryClientProvider>)}
describe("Script workspace",()=>{beforeEach(()=>vi.clearAllMocks());it("shows insufficient evidence without narration",async()=>{vi.mocked(projectApi.get).mockResolvedValue(project);vi.mocked(projectApi.scriptStatus).mockResolvedValue(base);vi.mocked(projectApi.script).mockResolvedValue({project_id:"p1",status:"NEEDS_REVIEW",version:"script-v1",generated_at:null,approved_at:null,script:{evidence_coverage:{available_facts:1,required_facts:12,available_sources:1,required_sources:7,recommended_max_duration_minutes:3},full_script:"",sections:[]}});view();expect(await screen.findByText("Evidence is insufficient")).toBeInTheDocument();expect(screen.getByText(/No padded script/)).toBeInTheDocument()});it("renders grounded narration and citation references",async()=>{vi.mocked(projectApi.get).mockResolvedValue({...project,status:"SCRIPT_COMPLETE"});vi.mocked(projectApi.scriptStatus).mockResolvedValue({...base,project_status:"SCRIPT_COMPLETE",script_status:"COMPLETE",evidence_sufficiency:"SUFFICIENT",available_facts:12,available_sources:7,actual_word_count:900,estimated_duration_minutes:6.2});vi.mocked(projectApi.script).mockResolvedValue({project_id:"p1",status:"COMPLETE",version:"script-v1",generated_at:null,approved_at:null,script:{title:"Pyramid Evidence",actual_word_count:900,estimated_duration_minutes:6.2,evidence_coverage:{status:"SUFFICIENT"},opening_hook:"What does the evidence establish?",introduction:"Follow the sources.",sections:[{heading:"Act 1",narration:"Approved fact.",visual_cue:"Show artifact",production_note:"Verify",source_ids:["src1"]}],ending:"Qualified conclusion.",call_to_action:"Discuss the evidence.",factual_warnings:["Verify"],production_notes:[],pronunciation_notes:[],limitations:[]}});view();expect(await screen.findByText("Approved fact.")).toBeInTheDocument();expect(screen.getByText(/src1/)).toBeInTheDocument();expect(screen.getByRole("button",{name:/approve script/i})).toBeInTheDocument()})});
