import{useMutation,useQuery,useQueryClient}from"@tanstack/react-query";
import{AlertTriangle,CheckCircle2,LoaderCircle,RefreshCw,XCircle}from"lucide-react";
const useNavigate=()=>(path:string)=>window.history.pushState({},"",path);
import{projectApi}from"./projectApi";

const list=(value:unknown)=>Array.isArray(value)?value:[];
const useAction=(fn:()=>Promise<unknown>,refresh:()=>void)=>useMutation({mutationFn:fn,onSuccess:refresh});
export default function ScriptWorkspace({projectId}:{projectId:string}){
 const client=useQueryClient();const navigate=useNavigate();
 const project=useQuery({queryKey:["project",projectId],queryFn:({signal})=>projectApi.get(projectId,signal)});
 const status=useQuery({queryKey:["script-status",projectId],queryFn:({signal})=>projectApi.scriptStatus(projectId,signal),enabled:Boolean(project.data&&!(["CREATED","RESEARCHING","RESEARCH_COMPLETE","PRODUCING_BRIEF","BRIEF_COMPLETE"].includes(project.data.status))),retry:false,refetchInterval:q=>["PENDING","GENERATING"].includes(q.state.data?.script_status??"")?2000:false});
 const visible=["COMPLETE","NEEDS_REVIEW","APPROVED","REJECTED","STALE"].includes(status.data?.script_status??"");
 const script=useQuery({queryKey:["script",projectId],queryFn:({signal})=>projectApi.script(projectId,signal),enabled:visible});
 const refresh=()=>{client.invalidateQueries({queryKey:["project",projectId]});client.invalidateQueries({queryKey:["script-status",projectId]});client.invalidateQueries({queryKey:["script",projectId]})};
 const start=useAction(()=>projectApi.startScript(projectId),refresh);const approve=useAction(()=>projectApi.approveScript(projectId),refresh);const retry=useAction(()=>projectApi.retryScript(projectId),refresh);const regenerate=useAction(()=>projectApi.regenerateScript(projectId),refresh);const reject=useAction(()=>projectApi.rejectScript(projectId),refresh);
 if(project.isPending)return <div className="panel p-6 text-muted">Loading Script stage…</div>;
 if(project.data?.status==="BRIEF_APPROVED"&&!status.data)return <div className="panel p-8"><h2 className="page-title">Documentary Script Writer</h2><p className="mt-3 text-sm text-muted">Generate narration only when approved evidence supports the duration.</p><button onClick={()=>start.mutate()} className="mt-7 rounded-lg bg-accent px-5 py-3 text-sm font-bold text-white">GENERATE SCRIPT</button></div>;
 if(!status.data)return <div className="panel p-8"><h2 className="page-title">Script locked</h2><p className="mt-3 text-sm text-muted">Approve the Production Brief before script generation.</p></div>;
 if(["PENDING","GENERATING"].includes(status.data.script_status))return <div><h2 className="page-title">Generating Script…</h2><div className="panel mt-6 flex items-center gap-4 p-6"><LoaderCircle className="h-5 w-5 animate-spin text-accent"/><p>{status.data.current_step.replaceAll("_"," ")} · {status.data.available_facts}/{status.data.required_facts} facts</p></div></div>;
 if(status.data.script_status==="FAILED")return <div className="panel p-8"><AlertTriangle className="text-danger"/><h2 className="mt-4 text-xl font-semibold">Script generation failed</h2><p className="mt-2 text-sm text-muted">{status.data.safe_error_message}</p><button onClick={()=>retry.mutate()} className="btn mt-5">RETRY</button></div>;
 if(script.isPending||!script.data)return <div className="panel p-6 text-muted">Loading script…</div>;
 const data=script.data.script;const coverage=data.evidence_coverage as Record<string,unknown>|undefined;
 if(script.data.status==="STALE")return <div className="panel border-warning/30 p-8"><AlertTriangle className="text-warning"/><h2 className="mt-4 text-xl font-semibold">Script is stale</h2><p className="mt-2 text-sm text-muted">Research or the Production Brief changed. Approve the revised brief, then regenerate Script {script.data.version}.</p></div>;
 if(script.data.status==="NEEDS_REVIEW")return <div className="panel border-warning/30 p-8"><AlertTriangle className="text-warning"/><h2 className="mt-4 text-xl font-semibold">Evidence is insufficient</h2><p className="mt-3 text-sm text-muted">No padded script was generated.</p><div className="mt-5 grid gap-3 sm:grid-cols-4">{[["Facts",`${String(coverage?.available_facts)}/${String(coverage?.required_facts)}`],["Sources",`${String(coverage?.available_sources)}/${String(coverage?.required_sources)}`],["Authoritative",`${String(coverage?.available_authoritative_sources)}/${String(coverage?.required_authoritative_sources)}`],["Recommended maximum",`${String(coverage?.recommended_max_duration_minutes)} minutes`]].map(([label,value])=><div className="rounded-lg bg-raised p-4" key={label}><p className="subtle-label">{label}</p><p className="mt-2 font-semibold">{value}</p></div>)}</div><button onClick={()=>navigate("?stage=Research&expand=1")} className="mt-6 rounded-lg bg-accent px-5 py-3 text-sm font-bold text-white">EXPAND RESEARCH</button></div>;
 return <div className="space-y-6"><div className="flex justify-between gap-4"><div><p className="subtle-label">Script · {script.data.version}</p><h2 className="page-title mt-2">{String(data.title)}</h2><p className="mt-2 text-sm text-muted">{String(data.actual_word_count)} words · {String(data.estimated_duration_minutes)} minutes</p></div>{script.data.status!=="APPROVED"&&<div className="flex gap-2"><button onClick={()=>reject.mutate()} className="btn text-danger"><XCircle className="h-4 w-4"/>REJECT</button><button onClick={()=>regenerate.mutate()} className="btn"><RefreshCw className="h-4 w-4"/>REGENERATE</button><button onClick={()=>approve.mutate()} className="rounded-lg bg-success px-4 py-2 text-sm font-bold text-white">APPROVE SCRIPT</button></div>}</div>
 {[['Opening Hook',data.opening_hook],['Introduction',data.introduction]].map(([title,text])=><section className="panel p-6" key={String(title)}><h3 className="section-title">{String(title)}</h3><p className="mt-4 text-sm leading-7">{String(text)}</p></section>)}
 <section className="space-y-4">{list(data.sections).map((item,index)=>{const section=item as Record<string,unknown>;return <article className="panel p-6" key={index}><h3 className="section-title">{String(section.heading)}</h3><p className="mt-4 text-sm leading-7">{String(section.narration)}</p><div className="mt-4 border-t border-line pt-4 text-xs text-muted"><p><strong>Visual:</strong> {String(section.visual_cue)}</p><p className="mt-2 text-accent"><strong>Citations:</strong> {list(section.source_ids).join(", ")}</p></div></article>})}</section>
 {[['Ending',data.ending],['Call to Action',data.call_to_action]].map(([title,text])=><section className="panel p-6" key={String(title)}><h3 className="section-title">{String(title)}</h3><p className="mt-4 text-sm leading-7">{String(text)}</p></section>)}
 {script.data.status==="APPROVED"&&<div className="flex items-center gap-3 rounded-xl border border-success/30 bg-success/10 p-5 text-success"><CheckCircle2 className="h-5 w-5"/><strong>Script approved · Storyboard unlocked but unimplemented.</strong></div>}</div>;
}
