import{useMutation}from"@tanstack/react-query";
import{ArrowRight,Clapperboard}from"lucide-react";
import{useState}from"react";
import{useNavigate}from"react-router-dom";
import{projectApi}from"./projectApi";

const choices={country:["United States","United Kingdom","Canada","Australia"],category:["Documentary","Education","Technology","Business","Entertainment"],language:["English","Spanish","French","German"],length:["8 Minutes","10 Minutes","15 Minutes","20 Minutes","30 Minutes"]};

export default function StudioHomePage(){const navigate=useNavigate();const[form,setForm]=useState({title:"",country:"United States",category:"Documentary",language:"English",target_length:"15 Minutes"});const create=useMutation({mutationFn:projectApi.create,onSuccess:project=>navigate(`/projects/${project.id}`)});const update=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));const submit=(event:React.FormEvent)=>{event.preventDefault();if(form.title.trim())create.mutate({...form,title:form.title.trim()})};return <div className="min-h-screen bg-canvas text-ink"><header className="flex h-20 items-center border-b border-line px-6 lg:px-12"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-accent text-white"><Clapperboard className="h-5 w-5"/></span><div><strong className="block tracking-tight">VIRALFORGE</strong><span className="text-[10px] font-bold uppercase tracking-[.2em] text-muted">Studio</span></div></div></header><main className="mx-auto flex max-w-5xl items-center justify-center px-5 py-16 lg:min-h-[calc(100vh-5rem)] lg:py-20"><section className="w-full"><div className="mb-10 text-center"><p className="subtle-label mb-3">ViralForge Studio</p><h1 className="text-4xl font-semibold tracking-[-.04em] lg:text-6xl">What video should we create today?</h1><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-muted">Start a focused production workspace. Research begins only when you ask for it.</p></div><form onSubmit={submit} className="panel mx-auto max-w-3xl p-6 lg:p-9"><label className="subtle-label" htmlFor="topic">Topic</label><input id="topic" required autoFocus className="input mt-2 h-14 text-base" placeholder="The Great Pyramid" value={form.title} onChange={event=>update("title",event.target.value)}/><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{([['country','Country',choices.country],['category','Category',choices.category],['language','Language',choices.language],['target_length','Target Length',choices.length]]as const).map(([key,label,options])=><label key={key}><span className="subtle-label">{label}</span><select className="input mt-2 h-11" value={form[key]} onChange={event=>update(key,event.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select></label>)}</div>{create.isError&&<p role="alert" className="mt-5 rounded-lg border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{create.error.message}</p>}<button disabled={create.isPending||!form.title.trim()} className="mt-8 inline-flex h-12 w-full items-center justify-center gap-2 rounded-lg bg-accent px-5 text-sm font-bold text-white disabled:opacity-50">{create.isPending?"CREATING PROJECT…":"START PROJECT"}<ArrowRight className="h-4 w-4"/></button></form></section></main></div>}
