import type{ReactNode}from"react";import{AlertTriangle,Database,Inbox,LoaderCircle,RefreshCw}from"lucide-react";import{formatName,pct}from"../lib/format";
export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description:string;actions?:ReactNode}){return <header className="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div>{eyebrow&&<p className="subtle-label mb-2 text-accent">{eyebrow}</p>}<h1 className="page-title">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">{description}</p></div>{actions}</header>}
export function StatusPill({status,label}:{status:"good"|"warn"|"bad"|"neutral";label:string}){const style={good:"bg-success/10 text-success border-success/20",warn:"bg-warning/10 text-warning border-warning/20",bad:"bg-danger/10 text-danger border-danger/20",neutral:"bg-raised text-muted border-line"}[status];return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2 py-1 text-[10px] font-bold uppercase tracking-[.08em] ${style}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{label}</span>}
export function DecisionBadge({type}:{type:string}){const normalized=type.toLowerCase();const style=normalized==="create"?"border-success/20 bg-success/10 text-success":normalized==="wait"||normalized==="monitor"?"border-warning/20 bg-warning/10 text-warning":"border-line bg-raised text-muted";return <span className={`inline-flex rounded-md border px-2 py-1 text-[10px] font-bold uppercase tracking-[.09em] ${style}`}>{formatName(type)}</span>}
export function MetricCard({label,value,detail,icon,tone="blue"}:{label:string;value:ReactNode;detail:string;icon:ReactNode;tone?:"blue"|"green"|"amber"}){const color={blue:"text-accent bg-accent/10",green:"text-success bg-success/10",amber:"text-warning bg-warning/10"}[tone];return <article className="panel p-4 lg:p-5"><div className="flex items-start justify-between"><span className="text-xs font-medium text-muted">{label}</span><span className={`rounded-lg p-2 ${color}`}>{icon}</span></div><strong className="mt-3 block text-2xl font-semibold tracking-tight text-ink">{value}</strong><span className="mt-1 block truncate text-[11px] text-muted">{detail}</span></article>}
export function LoadingState({rows=4}:{rows?:number}){return <div className="space-y-3" role="status" aria-label="Loading"><div className="h-5 w-40 animate-pulse rounded bg-raised"/>{Array.from({length:rows},(_,index)=><div key={index} className="h-12 animate-pulse rounded-lg bg-raised"/>)}</div>}
export function PageLoading(){return <div className="grid min-h-[45vh] place-items-center"><div className="flex items-center gap-2 text-sm text-muted"><LoaderCircle className="h-4 w-4 animate-spin"/>Loading intelligence…</div></div>}
export function EmptyState({title="No data yet",description="The intelligence pipeline has not produced records for this view."}:{title?:string;description?:string}){return <div className="grid min-h-48 place-items-center p-8 text-center"><div><Inbox className="mx-auto mb-3 h-7 w-7 text-muted"/><h3 className="text-sm font-semibold text-ink">{title}</h3><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-muted">{description}</p></div></div>}
export function ErrorState({error,retry}:{error:unknown;retry?:()=>void}){return <div className="panel grid min-h-56 place-items-center p-8 text-center"><div><AlertTriangle className="mx-auto mb-3 h-7 w-7 text-danger"/><h3 className="text-sm font-semibold">Unable to load intelligence</h3><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-muted">{error instanceof Error?error.message:"An unexpected error occurred."}</p>{retry&&<button className="btn mt-4" onClick={retry}><RefreshCw className="h-3.5 w-3.5"/>Retry</button>}</div></div>}
export function Progress({value}:{value:number}){const safe=Math.max(0,Math.min(100,value<=1?value*100:value));return <div className="h-1.5 overflow-hidden rounded-full bg-raised"><div className="h-full rounded-full bg-accent" style={{width:`${safe}%`}}/></div>}
export function Confidence({value}:{value:number}){return <div className="flex min-w-24 items-center gap-2"><Progress value={value}/><span className="text-xs text-muted">{pct(value)}</span></div>}
export function ConnectorBadge({name}:{name:string}){return <span className="inline-flex items-center gap-1.5 rounded-md border border-line bg-raised px-2 py-1 text-[11px] text-ink"><Database className="h-3 w-3 text-accent"/>{formatName(name)}</span>}
export function ChartCard({title,subtitle,children}:{title:string;subtitle?:string;children:ReactNode}){return <article className="panel-pad min-w-0"><div className="mb-5"><h2 className="section-title">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-muted">{subtitle}</p>}</div>{children}</article>}
